### ISSUE TITLE
DistMult Streambatcher

### ISSUE THREAD

**Issue by snash4** [yangji9181/HNE#1]
Hi, 
 I followed your steps in running the DistMult. I got this error
File "src/main.py", line 182, in <module>
    main(args)
  File "src/main.py", line 83, in main
    train_batcher = StreamBatcher(args.data, 'train', args.batch_size, randomize=True, keys=input_keys, loader_threads=args.loader_threads)
  File ".....HNE/Model/DistMult/src/spodernet/spodernet/preprocessing/batching.py", line 217, in __init__
    log.error('Path {0} does not exists! Have you forgotten to preprocess your dataset?', config_path)
  File "....HNE/Model/DistMult/src/spodernet/spodernet/utils/logger.py", line 106, in error
    raise Exception(message.format(*args))
Exception: Path ...../.data/PubMed/train/hdf5_config.pkl does not exists! Have you forgotten to preprocess your dataset?
Exception ignored in: <bound method StreamBatcher.__del__ of <spodernet.preprocessing.batching.StreamBatcher object at 0x7f4869e3b5c0>>
Traceback (most recent call last):
  File ".....HNE/Model/DistMult/src/spodernet/spodernet/preprocessing/batching.py", line 268, in __del__
    for worker in self.loaders:
AttributeError: 'StreamBatcher' object has no attribute 'loaders'

**Comment by xiaoyuxin1002** [comment]
Sorry, the order of preprocessing and execution was wrong. 
The problem should be fixed now.
Thanks!

**Comment by snash4** [comment]
thanks !
