### ISSUE TITLE
R-GCN  RuntimeError: Found dtype Long but expected Float

### ISSUE THREAD

**Issue by Qidong-Liu** [yangji9181/HNE#13]
Dataset: Yelp

Supervised = 'True'

Traceback (most recent call last):
  File "src/main.py", line 188, in <module>
    main(args)
  File "src/main.py", line 94, in main
    if args.supervised=='True': loss = model.get_supervised_loss(pred, matched_labels, matched_index, multi)
  File "/home/lqd/code/HNE-master/Model/R-GCN/src/model.py", line 142, in get_supervised_loss
    predict_loss = F.binary_cross_entropy(torch.sigmoid(embed[matched_index]), matched_labels)
  File "/home/lqd/software/anaconda3/envs/HNE/lib/python3.7/site-packages/torch/nn/functional.py", line 2526, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: Found dtype Long but expected Float

**Comment by xiaoyuxin1002** [comment]
Thanks for bringing it out! The bug has been fixed.
