### ISSUE TITLE
DistMult running error

### ISSUE THREAD

**Issue by null-id** [yangji9181/HNE#9]
```bash
Traceback (most recent call last):
  File "src/main.py", line 13, in <module>
    from spodernet.hooks import LossHook, ETAHook
  File "/home/usr/anaconda3/lib/python3.7/site-packages/spodernet/hooks.py", line 6, in <module>
    from spodernet.utils.util import Timer
ModuleNotFoundError: No module named 'spodernet.utils'
```

**Comment by xiaoyuxin1002** [comment]
You need to install the required packages as stated in the README of our DistMult repository.

**Comment by null-id** [comment]
I installed. However,

```python
>>> import spodernet
>>> import spodernet.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spodernet.utils'
```

As you can see, spodernet is imported normally. But utils not found.
